### ISSUE TITLE
Why the CLS embedding is from the 1-th index instead of 0-th index?

### ISSUE THREAD

**Issue by scottjiao** [microsoft/GraphFormers#5]
https://github.com/microsoft/GraphFormers/blob/06636cd7196cc2b3eecdb5a49fd2d405d2ea4e4b/src/models/modeling_graphformers.py#L157

**Comment by SamuelYang1** [comment]
the 0th is GNN-processed node-level embeddings


>
https://github.com/microsoft/GraphFormers/blob/06636cd7196cc2b3eecdb5a49fd2d405d2ea4e4b/src/models/modeling_graphformers.py#L257
We pad it in front of the original input sequence before encoding.

**Comment by scottjiao** [comment]
Thank u for answering : )
